"""Initial migration

Revision ID: b818d2b571cd
Revises: 975f270d7efb
Create Date: 2026-07-20 23:18:41.172981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b818d2b571cd'
down_revision: Union[str, None] = '975f270d7efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_matches_student_request_parent_travel', 'matches', ['student_request_id', 'parent_travel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_matches_student_request_parent_travel', 'matches', type_='unique')
    # ### end Alembic commands ###
